import Mathlib
import PrimeArithmetic.Sieve.BoundedByteFamilies

namespace PrimeArithmetic.Sieve

/-!
Aggregated same-byte mask families for sieve-style bitsets.

`BoundedByteFamilies.lean` treats a family of writes one marked bit at a time.
That is exact, but the runtime meaning is often cleaner when repeated writes to
the same byte are grouped into a single OR-mask update. This module packages
that cleaner route.

The scope is still intentionally small:

- build one OR-mask from a finite list of target bits in a byte
- update one bounded byte slot by ORing in that combined mask
- prove that every listed bit reads back as `1`
- prove that unlisted bits in the same byte are unchanged
- show that the repeated same-byte write family collapses to the aggregated mask

This handles same-byte collisions directly and leaves the next step as
multi-byte grouped plans rather than long single-bit write traces.
-/

/-- Combined OR-mask generated by a finite list of target bits in a byte. -/
def bitsMask : List (Fin 8) → ℕ
  | [] => 0
  | bit :: bits => (1 <<< bit.1) ||| bitsMask bits

/-- Single bounded-byte update using an already aggregated mask. -/
def byteMaskWrite {byteCount : ℕ} (bytes : BoundedByteState byteCount)
    (slot : Fin byteCount) (mask : ℕ) : BoundedByteState byteCount :=
  Function.update bytes slot (bytes slot ||| mask)

/-- Same-byte mark family generated from one bounded slot and a list of bits. -/
def byteMarksAt {byteCount : ℕ} (slot : Fin byteCount) : List (Fin 8) → List (ByteMark byteCount)
  | [] => []
  | bit :: bits => (slot, bit) :: byteMarksAt slot bits

theorem bitsMask_testBit_of_mem (bits : List (Fin 8)) (target : Fin 8)
    (hMem : target ∈ bits) :
    (bitsMask bits).testBit target.1 = true := by
  induction bits generalizing target with
  | nil =>
      cases hMem
  | cons bit bits ih =>
      rw [List.mem_cons] at hMem
      cases hMem with
      | inl hEq =>
          subst hEq
          rw [bitsMask, Nat.testBit_lor]
          have hSelf : ((1 <<< target.1).testBit target.1) = true := by
            simp [Nat.shiftLeft_eq]
          rw [hSelf]
          simp
      | inr hTail =>
          rw [bitsMask, Nat.testBit_lor]
          have hTailBit : (bitsMask bits).testBit target.1 = true := ih target hTail
          rw [hTailBit]
          simp

theorem bitsMask_testBit_of_not_mem (bits : List (Fin 8)) (target : Fin 8)
    (hNot : target ∉ bits) :
    (bitsMask bits).testBit target.1 = false := by
  induction bits generalizing target with
  | nil =>
      simp [bitsMask]
  | cons bit bits ih =>
      simp at hNot
      rcases hNot with ⟨hNe, hTail⟩
      rw [bitsMask, Nat.testBit_lor]
      have hHead : ((1 <<< bit.1).testBit target.1) = false := by
        simpa [Nat.shiftLeft_eq] using
          (Nat.testBit_two_pow_of_ne <| by
            intro hEq
            apply hNe
            exact (Fin.ext hEq).symm)
      simp [hHead, ih target hTail]

@[simp] theorem bitsMask_testBit_iff (bits : List (Fin 8)) (target : Fin 8) :
    (bitsMask bits).testBit target.1 = true ↔ target ∈ bits := by
  constructor
  · intro hBit
    by_cases hMem : target ∈ bits
    · exact hMem
    · rw [bitsMask_testBit_of_not_mem bits target hMem] at hBit
      cases hBit
  · intro hMem
    exact bitsMask_testBit_of_mem bits target hMem

theorem byteMaskWrite_zero {byteCount : ℕ} (bytes : BoundedByteState byteCount)
    (slot : Fin byteCount) :
    byteMaskWrite bytes slot 0 = bytes := by
  funext byteSlot
  by_cases h : byteSlot = slot
  · subst h
    simp [byteMaskWrite, Function.update]
  · simp [byteMaskWrite, Function.update, h]

theorem byteMarkRead_written_by_mask_of_testBit {byteCount : ℕ}
    (bytes : BoundedByteState byteCount) (slot : Fin byteCount) (bit : Fin 8)
    (mask : ℕ) (hMask : mask.testBit bit.1 = true) :
    byteMarkRead (byteMaskWrite bytes slot mask) (slot, bit) = 1 := by
  rw [byteMarkRead_eq_toNat_testBit]
  unfold byteMaskWrite
  simp [Function.update, hMask]

theorem byteMarkRead_written_by_bits_of_mem {byteCount : ℕ}
    (bytes : BoundedByteState byteCount) (slot : Fin byteCount)
    (bits : List (Fin 8)) (target : Fin 8) (hMem : target ∈ bits) :
    byteMarkRead (byteMaskWrite bytes slot (bitsMask bits)) (slot, target) = 1 := by
  exact byteMarkRead_written_by_mask_of_testBit bytes slot target (bitsMask bits)
    (bitsMask_testBit_of_mem bits target hMem)

theorem byteMarkRead_same_slot_eq_of_not_mem_bits {byteCount : ℕ}
    (bytes : BoundedByteState byteCount) (slot : Fin byteCount)
    (bits : List (Fin 8)) (target : Fin 8) (hNot : target ∉ bits) :
    byteMarkRead (byteMaskWrite bytes slot (bitsMask bits)) (slot, target) =
      byteMarkRead bytes (slot, target) := by
  rw [byteMarkRead_eq_toNat_testBit, byteMarkRead_eq_toNat_testBit]
  unfold byteMaskWrite
  simp [Function.update, bitsMask_testBit_of_not_mem bits target hNot]

theorem byteMarkRead_preserved_by_mask_other_byte {byteCount : ℕ}
    (bytes : BoundedByteState byteCount) (target : ByteMark byteCount)
    (slot : Fin byteCount) (mask : ℕ) (hSlot : target.1 ≠ slot)
    (hRead : byteMarkRead bytes target = 1) :
    byteMarkRead (byteMaskWrite bytes slot mask) target = 1 := by
  unfold byteMaskWrite byteMarkRead at *
  simp [Function.update, hSlot, hRead]

theorem byteMarkWriteMany_at_eq_byteMaskWrite {byteCount : ℕ}
    (bytes : BoundedByteState byteCount) (slot : Fin byteCount)
    (bits : List (Fin 8)) :
    byteMarkWriteMany bytes (byteMarksAt slot bits) =
      byteMaskWrite bytes slot (bitsMask bits) := by
  induction bits generalizing bytes with
  | nil =>
      simp [byteMarksAt, byteMarkWriteMany, bitsMask, byteMaskWrite_zero]
  | cons bit bits ih =>
      simp [byteMarksAt, byteMarkWriteMany, bitsMask]
      rw [ih]
      funext byteSlot
      by_cases h : byteSlot = slot
      · subst h
        simp [byteMaskWrite, byteMarkWrite, Function.update, Nat.lor_assoc]
      · simp [byteMaskWrite, byteMarkWrite, Function.update, h]

theorem byteMarkRead_of_mem_writeMany_at {byteCount : ℕ}
    (bytes : BoundedByteState byteCount) (slot : Fin byteCount)
    (bits : List (Fin 8)) (target : Fin 8) (hMem : target ∈ bits) :
    byteMarkRead (byteMarkWriteMany bytes (byteMarksAt slot bits)) (slot, target) = 1 := by
  rw [byteMarkWriteMany_at_eq_byteMaskWrite]
  exact byteMarkRead_written_by_bits_of_mem bytes slot bits target hMem

theorem byteMarkRead_writeMany_at_eq_of_not_mem {byteCount : ℕ}
    (bytes : BoundedByteState byteCount) (slot : Fin byteCount)
    (bits : List (Fin 8)) (target : Fin 8) (hNot : target ∉ bits) :
    byteMarkRead (byteMarkWriteMany bytes (byteMarksAt slot bits)) (slot, target) =
      byteMarkRead bytes (slot, target) := by
  rw [byteMarkWriteMany_at_eq_byteMaskWrite]
  exact byteMarkRead_same_slot_eq_of_not_mem_bits bytes slot bits target hNot

end PrimeArithmetic.Sieve
