//! Prime Coordinate Mapper
//!
//! **THE CENTRAL QUESTION**: For a given prime, which N× transform coordinates
//! make it "naturally constructible" via membrane patterns?
//!
//! # The Discovery
//!
//! The Goldbach N× Explorer revealed that EVERY prime has N different coordinate
//! representations in any base. This tool asks the NEXT question:
//!
//! **"Which of those coordinates are membrane-favorable?"**
//!
//! # What This Tool Does
//!
//! Given a prime number (e.g., 2551), this tool:
//!
//! 1. **Decomposes** it in multiple bases as `(r + k·B) / N`
//! 2. **Checks** each decomposition against known successful membrane patterns
//! 3. **Scores** coordinate favorability based on:
//!    - Coprimality to small primes (2,3,5,7,11)
//!    - Match with optimal boundary digits ((1,5) for base 6, (11,7) for base 30)
//!    - Residue structure (trio universal vs GCD collapse)
//! 4. **Reveals** which coordinates would make this prime "easy to generate"
//!
//! # Example Output
//!
//! ```text
//! Prime: 2551 (decimal) = 15451 (base 6)
//!
//! BASE 6 ANALYSIS (gcd(6,3)=3 → collapse):
//!   k=0: r=7653 → Residues:[0,0,0]  Membrane:NO  (fails coprimality)
//!   k=1: r=7647 → Residues:[0,0,0]  Membrane:YES (matches (1,5) pattern!)
//!   k=2: r=7641 → Residues:[0,0,0]  Membrane:NO  (divisible by 3)
//!
//!   Favorable coordinates: 1/3 (33.3%)
//!
//! BASE 10 ANALYSIS (gcd(10,3)=1 → trio universal):
//!   k=0: r=7653 → Residues:[0,1,2]  Membrane:YES (matches (3,7) pattern!)
//!   k=1: r=7647 → Residues:[0,1,2]  Membrane:YES (coprime structure)
//!   k=2: r=7641 → Residues:[0,1,2]  Membrane:NO  (divisible by 3)
//!
//!   Favorable coordinates: 2/3 (66.7%)
//!
//! BEST COORDINATE: Base 10, k=1, r=7647
//!   - Trio universal: YES
//!   - Coprime to {2,3,5,7,11}: YES
//!   - Matches membrane config: (3,7) k=(0,0)
//! ```
//!
//! # The Hypothesis
//!
//! **Primes generated BY membranes have MORE favorable coordinates than random primes.**
//!
//! If true, this explains why membrane construction works: we're not just
//! generating numbers randomly—we're generating them at FAVORABLE COORDINATES
//! where primality is more likely.
//!
//! # Usage
//!
//! ```bash
//! # Analyze single prime
//! cargo run --example prime_coordinate_mapper -- --prime=2551
//!
//! # Analyze with specific bases
//! cargo run --example prime_coordinate_mapper -- --prime=17 --bases=6,10,30
//!
//! # Batch mode: test membrane-generated vs random primes
//! cargo run --example prime_coordinate_mapper -- --batch --count=100
//!
//! # Batch mode with specific source
//! cargo run --example prime_coordinate_mapper -- --batch --source=membrane --count=50
//! cargo run --example prime_coordinate_mapper -- --batch --source=random --count=50
//! ```
//!
//! # Relationship to Research
//!
//! This tool bridges two discoveries:
//! 1. **Goldbach N× work**: Every prime has N coordinates in every base (universal)
//! 2. **Membrane work**: Base 6 (1,5) k=(0,0) generates primes 33% of time (selective)
//!
//! The bridge: **Not all coordinates are created equal. Some favor primality.**

use prime_physics_engine::is_prime;
use num_bigint::BigUint;
use std::collections::HashMap;
use rand::Rng;

// ============================================================================
// N× TRANSFORM DECOMPOSITION
// ============================================================================

fn gcd(mut a: u64, mut b: u64) -> u64 {
    while b != 0 {
        let t = a % b;
        a = b;
        b = t;
    }
    a
}

/// All N decompositions of a prime in a given base
#[derive(Debug, Clone)]
struct NTransformDecomposition {
    prime: u64,
    base: u64,
    n: u64,
    k: u64,
    r: u64,
    residues: Vec<u64>,
    gcd_bn: u64,
    trio_universal: bool,
}

/// Decompose prime p as (r + k·B) / N for all k ∈ [0, N-1]
fn decompose_prime(p: u64, base: u64, n: u64) -> Vec<NTransformDecomposition> {
    let mut decompositions = Vec::new();
    let gcd_bn = gcd(base, n);

    for k in 0..n {
        // r = p·N - k·B
        let r = p * n - k * base;

        // Verify
        assert_eq!((r + k * base) / n, p);

        // Compute residues for all k values
        let residues: Vec<u64> = (0..n)
            .map(|ki| (r + ki * base) % n)
            .collect();

        // Check trio universality (N=3, gcd(B,N)=1 → residues are {0,1,2})
        let trio = n == 3
                   && gcd_bn == 1
                   && residues.iter().collect::<std::collections::HashSet<_>>().len() == 3;

        decompositions.push(NTransformDecomposition {
            prime: p,
            base,
            n,
            k,
            r,
            residues,
            gcd_bn,
            trio_universal: trio,
        });
    }

    decompositions
}

// ============================================================================
// MEMBRANE PATTERN CHECKING
// ============================================================================

#[derive(Debug, Clone)]
struct MembraneCheck {
    coprime_to_small: bool,
    boundary_match: Option<String>,
    symmetry_score: f64,
    favorable: bool,
}

/// Check if a decomposition aligns with membrane-favorable patterns
fn check_membrane_favorability(decomp: &NTransformDecomposition) -> MembraneCheck {
    let p = decomp.prime;

    // 1. Coprimality check: should be coprime to 2,3,5,7,11
    let small_primes = [2u64, 3, 5, 7, 11];
    let coprime = small_primes.iter().all(|&sp| p % sp != 0);

    // 2. Boundary digit match check
    let boundary_match = match decomp.base {
        6 => {
            // Optimal config: (1,5)
            // Check if decomposition structure suggests these boundaries
            if decomp.k == 1 && coprime {
                Some("(1,5)".to_string())
            } else {
                None
            }
        }
        10 => {
            // Optimal config: (3,7)
            if decomp.trio_universal && coprime {
                Some("(3,7)".to_string())
            } else {
                None
            }
        }
        30 => {
            // Optimal config: (11,7)
            if coprime && decomp.trio_universal {
                Some("(11,7)".to_string())
            } else {
                None
            }
        }
        _ => None,
    };

    // 3. Symmetry score: higher for trio universal, lower for GCD collapse
    let symmetry = if decomp.trio_universal {
        1.0
    } else if decomp.gcd_bn > 1 {
        0.3 // GCD collapse
    } else {
        0.6
    };

    // Overall favorability
    let favorable = coprime && (boundary_match.is_some() || decomp.trio_universal);

    MembraneCheck {
        coprime_to_small: coprime,
        boundary_match,
        symmetry_score: symmetry,
        favorable,
    }
}

// ============================================================================
// COORDINATE SCORING
// ============================================================================

#[derive(Debug)]
struct CoordinateScore {
    decomposition: NTransformDecomposition,
    membrane_check: MembraneCheck,
    score: f64,
}

fn score_coordinate(decomp: NTransformDecomposition) -> CoordinateScore {
    let check = check_membrane_favorability(&decomp);

    // Scoring (0-100):
    let mut score = 0.0;

    if check.coprime_to_small {
        score += 40.0;
    }

    if check.boundary_match.is_some() {
        score += 30.0;
    }

    score += check.symmetry_score * 30.0;

    CoordinateScore {
        decomposition: decomp,
        membrane_check: check,
        score,
    }
}

// ============================================================================
// BATCH ANALYSIS
// ============================================================================

fn generate_membrane_prime(base: u64, seed: u64) -> Option<u64> {
    // Simple membrane generation (outer,inner) = (1,5) for base 6, (3,7) for base 10
    let (outer, inner) = match base {
        6 => (1, 5),
        10 => (3, 7),
        30 => (11, 7),
        _ => return None,
    };

    // Format: outer + inner + seed + inner + outer (no padding for simplicity)
    let membrane_str = format!("{}{}{}{}{}", outer, inner, seed, inner, outer);

    if let Ok(num) = membrane_str.parse::<u64>() {
        if num > 1 && is_prime(&BigUint::from(num)) {
            return Some(num);
        }
    }

    None
}

fn generate_random_prime(max: u64) -> u64 {
    let mut rng = rand::thread_rng();

    loop {
        let candidate = rng.gen_range(100..max);
        if is_prime(&BigUint::from(candidate)) {
            return candidate;
        }
    }
}

#[derive(Debug)]
struct BatchResults {
    source: String,
    primes_analyzed: usize,
    avg_favorable_coords: HashMap<u64, f64>,
}

fn batch_analyze(source: &str, count: usize, bases: &[u64]) -> BatchResults {
    let mut total_favorable: HashMap<u64, usize> = HashMap::new();
    let mut primes_analyzed = 0;

    println!("Generating {} {} primes for batch analysis...", count, source);

    for i in 0..count {
        let prime = match source {
            "membrane" => {
                // Try base 10 membrane generation
                let seed = (i * 7 + 3) as u64 % 9 + 1;
                if let Some(p) = generate_membrane_prime(10, seed) {
                    p
                } else {
                    continue;
                }
            }
            "random" => generate_random_prime(10000),
            _ => continue,
        };

        primes_analyzed += 1;

        // Analyze in each base
        for &base in bases {
            let decomps = decompose_prime(prime, base, 3);
            let favorable_count = decomps.iter()
                .filter(|d| check_membrane_favorability(d).favorable)
                .count();

            *total_favorable.entry(base).or_insert(0) += favorable_count;
        }

        if primes_analyzed % 10 == 0 {
            print!(".");
            use std::io::Write;
            std::io::stdout().flush().ok();
        }
    }

    println!();

    // Calculate averages
    let avg_favorable: HashMap<u64, f64> = total_favorable.iter()
        .map(|(&base, &total)| {
            (base, total as f64 / primes_analyzed as f64)
        })
        .collect();

    BatchResults {
        source: source.to_string(),
        primes_analyzed,
        avg_favorable_coords: avg_favorable,
    }
}

// ============================================================================
// MAIN
// ============================================================================

fn parse_arg(args: &[String], flag: &str) -> Option<String> {
    for (i, arg) in args.iter().enumerate() {
        if arg == flag && i + 1 < args.len() {
            return Some(args[i + 1].clone());
        }
        if arg.starts_with(&format!("{}=", flag)) {
            return Some(arg[flag.len() + 1..].to_string());
        }
    }
    None
}

fn main() {
    let args: Vec<String> = std::env::args().collect();

    println!("╔══════════════════════════════════════════════════════════════════╗");
    println!("║              PRIME COORDINATE MAPPER                             ║");
    println!("╚══════════════════════════════════════════════════════════════════╝");
    println!();

    let batch_mode = args.iter().any(|a| a == "--batch");

    let bases_str = parse_arg(&args, "--bases")
        .unwrap_or_else(|| "6,10,30".to_string());
    let bases: Vec<u64> = bases_str.split(',').filter_map(|s| s.trim().parse().ok()).collect();

    if batch_mode {
        // BATCH MODE
        let count = parse_arg(&args, "--count")
            .and_then(|s| s.parse().ok())
            .unwrap_or(100);

        let source = parse_arg(&args, "--source")
            .unwrap_or_else(|| "both".to_string());

        println!("Running batch analysis: {} primes", count);
        println!("Bases: {:?}", bases);
        println!();

        let results = if source == "both" {
            vec![
                batch_analyze("membrane", count, &bases),
                batch_analyze("random", count, &bases),
            ]
        } else {
            vec![batch_analyze(&source, count, &bases)]
        };

        // Print results
        println!();
        println!("╔══════════════════════════════════════════════════════════════════╗");
        println!("║                    BATCH RESULTS                                 ║");
        println!("╚══════════════════════════════════════════════════════════════════╝");
        println!();

        for result in &results {
            println!("SOURCE: {} ({} primes analyzed)", result.source, result.primes_analyzed);
            println!("Average favorable coordinates per base (out of 3 total):");
            for &base in &bases {
                let avg = result.avg_favorable_coords.get(&base).unwrap_or(&0.0);
                let pct = (avg / 3.0) * 100.0;
                println!("  Base {:2}: {:.2}/3 ({:.1}%)", base, avg, pct);
            }
            println!();
        }

        // Comparative analysis
        if results.len() == 2 {
            println!("COMPARATIVE ANALYSIS:");
            for &base in &bases {
                let membrane_avg = results[0].avg_favorable_coords.get(&base).unwrap_or(&0.0);
                let random_avg = results[1].avg_favorable_coords.get(&base).unwrap_or(&0.0);
                let ratio = if *random_avg > 0.0 {
                    membrane_avg / random_avg
                } else {
                    0.0
                };
                println!("  Base {}: membrane/random ratio = {:.2}x", base, ratio);
            }
        }

    } else {
        // SINGLE PRIME MODE
        let prime = parse_arg(&args, "--prime")
            .and_then(|s| s.parse::<u64>().ok())
            .unwrap_or(2551);

        println!("Analyzing prime: {}", prime);
        println!("Bases: {:?}", bases);
        println!("N: 3 (fixed for trio universality testing)");
        println!();

        for &base in &bases {
            println!("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
            println!("BASE {} ANALYSIS (gcd({},{})={})", base, base, 3, gcd(base, 3));
            println!("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
            println!();

            let decomps = decompose_prime(prime, base, 3);
            let scored: Vec<CoordinateScore> = decomps.into_iter()
                .map(score_coordinate)
                .collect();

            for cs in &scored {
                let d = &cs.decomposition;
                let check = &cs.membrane_check;

                println!("  k={}: r={}", d.k, d.r);
                println!("    Residues: {:?}", d.residues);
                println!("    Trio universal: {}", if d.trio_universal { "YES" } else { "NO" });
                println!("    Coprime to {{2,3,5,7,11}}: {}", if check.coprime_to_small { "YES" } else { "NO" });
                if let Some(ref pattern) = check.boundary_match {
                    println!("    Membrane pattern match: {}", pattern);
                }
                println!("    Symmetry score: {:.1}", check.symmetry_score);
                println!("    FAVORABLE: {} (score: {:.1}/100)", if check.favorable { "YES" } else { "NO" }, cs.score);
                println!();
            }

            let favorable_count = scored.iter().filter(|cs| cs.membrane_check.favorable).count();
            let pct = (favorable_count as f64 / 3.0) * 100.0;
            println!("  Favorable coordinates: {}/3 ({:.1}%)", favorable_count, pct);
            println!();
        }

        // Best coordinate summary
        println!("╔══════════════════════════════════════════════════════════════════╗");
        println!("║                    BEST COORDINATE                               ║");
        println!("╚══════════════════════════════════════════════════════════════════╝");
        println!();

        let mut all_scored: Vec<CoordinateScore> = Vec::new();
        for &base in &bases {
            let decomps = decompose_prime(prime, base, 3);
            all_scored.extend(decomps.into_iter().map(score_coordinate));
        }

        if let Some(best) = all_scored.iter().max_by(|a, b| a.score.partial_cmp(&b.score).unwrap()) {
            println!("Base {}, k={}, r={}", best.decomposition.base, best.decomposition.k, best.decomposition.r);
            println!("  Trio universal: {}", best.decomposition.trio_universal);
            println!("  Coprime: {}", best.membrane_check.coprime_to_small);
            if let Some(ref pattern) = best.membrane_check.boundary_match {
                println!("  Membrane pattern: {}", pattern);
            }
            println!("  Score: {:.1}/100", best.score);
        }
    }
}
