{-# OPTIONS --safe #-}

-- BifurcationRoster:
--   Formal registry distinguishing certified universal (k*=0) configurations
--   from exceptional frontier (elbow) configurations.
--
-- This module provides the Agda incarnation of the bifurcation architecture
-- described in COLLABORATION.md and ridge_statistics.txt:
--
--   - Certified Universal Regime: Configurations with k*=0 for all M
--   - Exceptional Frontier: Configurations with detected elbows
--
-- For the current package (Base 15, outer=13, inner=1):
--   - ridge_statistics.txt reports:
--       Total configurations: 1
--       Configurations with k*=0 universality: 0
--       Configurations with ≥1 elbow:          1
--       → 100% exceptional frontier
--
-- This module encodes that split directly, with hooks for future expansion
-- when more configurations are analyzed.

module Theorems.BifurcationRoster where

open import Data.Nat using (ℕ; zero; suc)
open import Data.List using (List; []; _∷_)
open import Relation.Binary.PropositionalEquality using (_≡_; refl; _≢_)
open import Data.Empty using (⊥)

open import Theorems.RationalStatistics using (ℚ)
open import Theorems.ElbowEvents
open import Theorems.ElbowsFromCSV
open import Theorems.GlobalElbowFacts

-- Future integration with Abstract framework (ready to uncomment):
--
-- open import Theorems.Abstract.WindowCertificate
--   using (DualCertificate; WindowData; StaticCertificate; DynamicCertificate)
-- open import Theorems.Abstract.ConstrainedOrbitals
--   using (StableOrbital; InZone; Inviolability)

------------------------------------------------------------------------
-- 1. Bifurcation tags: certified vs exceptional
------------------------------------------------------------------------

-- The two regimes in the bifurcation architecture:
--
--   CertifiedUniversal:  k* = 0 for all M (proven via DualCertificate)
--   ExceptionalFrontier: ≥1 elbow detected (empirical ridge_extractor)

data Regime : Set where
  CertifiedUniversal  : Regime
  ExceptionalFrontier : Regime

------------------------------------------------------------------------
-- 2. Window identification key
------------------------------------------------------------------------

-- Minimal key identifying a residue window by (base, outer, inner).
-- This allows us to cross-reference ElbowConfig instances with
-- certified window data.

record WindowKey : Set where
  constructor mkWindowKey
  field
    baseK  : ℕ
    outerK : ℕ
    innerK : ℕ

open WindowKey public

-- Extract the window key from an elbow configuration

keyOfConfig : ElbowConfig → WindowKey
keyOfConfig c = mkWindowKey (base c) (outer c) (inner c)

------------------------------------------------------------------------
-- 3. Frontier roster from GlobalElbowFacts
------------------------------------------------------------------------

-- The current collab package has exactly one elbow event from
-- ridge_elbows.csv:
--
--   Base 15, (outer,inner) = (13,1), M=1→2, k=0→1
--
-- This is auto-generated by generate_elbow_agda_from_csv.py as:
--
--   elbow_b15_o13_i1_M1_to_M2_k0_to_k1 : ElbowEvent
--
-- in ElbowsFromCSV.agda, and designated as the flagship elbow in
-- GlobalElbowFacts.agda as `frontierElbow`.

-- We import frontierElbow from GlobalElbowFacts (no need to redefine)
open Theorems.GlobalElbowFacts using (frontierElbow)

frontierKey : WindowKey
frontierKey = keyOfConfig (cfg frontierElbow)

-- For this package (1 config, 1 elbow), the frontier roster is just
-- this single event. As ridge_elbows.csv grows, this list will expand
-- via allElbowEvents from ElbowsFromCSV.

frontierElbows : List ElbowEvent
frontierElbows = frontierElbow ∷ []

frontierRegime : Regime
frontierRegime = ExceptionalFrontier

------------------------------------------------------------------------
-- 4. Certified windows: placeholder for future integration
------------------------------------------------------------------------

-- A "certified window" is a residue window for which we have a
-- DualCertificate from the Abstract framework (WindowCertificate /
-- CertifiedResonanceComplete).
--
-- In the current collab snapshot:
--   - All certified examples (base 6, etc.) live in agda-proofs/
--   - They are NOT the (15,13,1) configuration analyzed here
--   - ridge_statistics.txt reports 0 certified universal configs
--
-- So for this package, the certified roster is empty, matching the
-- documented bifurcation split.

-- Minimal concrete type for future WindowCertificate integration.
-- When the Abstract framework is wired in, this will be extended with:
--   n    : ℕ
--   cert : DualCertificate n
--
-- For now, we just track the window key.

record CertifiedWindow : Set where
  constructor mkCertifiedWindow
  field
    key : WindowKey

open CertifiedWindow public

certifiedWindows : List CertifiedWindow
certifiedWindows = []

------------------------------------------------------------------------
-- 5. Current bifurcation snapshot
------------------------------------------------------------------------

-- This module formalizes the exact state described in ridge_statistics.txt:
--
--   frontierKey (Base 15, outer=13, inner=1) ↦ ExceptionalFrontier
--   certifiedWindows = []
--
-- As the dataset grows:
--   - New ElbowEvent values will be added via ElbowsFromCSV.agda
--   - New CertifiedWindow values will be exported from WindowCertificate
--   - The bifurcation theorem (certified and elbows are disjoint) can
--     be proven once the bridge logic is implemented

------------------------------------------------------------------------
-- 6. Future extension: the no-overlap theorem
------------------------------------------------------------------------

-- Once the Abstract framework integration is complete, uncomment the
-- imports above and add:
--
-- postulate
--   SameWindow :
--     CertifiedWindow → ElbowConfig → Set
--
--   extractStableOrbital :
--     (cw : CertifiedWindow) (e : ElbowEvent) →
--     SameWindow cw (cfg e) →
--     StableOrbital (cert cw) (k-to (cfg e))
--
-- noCertifiedElbow :
--   (cw : CertifiedWindow) (e : ElbowEvent) →
--   SameWindow cw (cfg e) →
--   k-to (cfg e) ≢ zero →
--   ⊥
-- noCertifiedElbow cw e same k≢0 =
--   -- Use Inviolability from ConstrainedOrbitals to derive contradiction
--   -- between k>0 stable orbital and k*=0 certification
--   ?
--
-- This would formalize: "No window can simultaneously be certified
-- universal (k*=0 for all M) and host an elbow (k jumps outward)."
--
-- That is the Agda incarnation of the bifurcation architecture.
