{-# OPTIONS --safe #-}

-- Auto-generated by generate_elbow_agda_from_csv.py
-- DO NOT EDIT BY HAND (or do, but then keep that in mind)

module Theorems.ElbowsFromCSV where

open import Data.Nat using (ℕ)
open import Relation.Binary.PropositionalEquality using (refl)
open import Theorems.RationalStatistics using (ℚ; _/_)
open import Theorems.ElbowEvents

-- Note: k-step-suc (generic n < suc n proof) is imported from Theorems.ElbowEvents

-- Event 1: base=15, outer=13, inner=1, M=1→2, k=0→1
cfg_b15_o13_i1_M1_to_M2_k0_to_k1 : ElbowConfig
cfg_b15_o13_i1_M1_to_M2_k0_to_k1 = mkElbowConfig 15 13 1 1 2 0 1

ρ_b15_o13_i1_M1_to_M2_k0_to_k1_from : ℚ
ρ_b15_o13_i1_M1_to_M2_k0_to_k1_from = 1 / 7

ρ_b15_o13_i1_M1_to_M2_k0_to_k1_to : ℚ
ρ_b15_o13_i1_M1_to_M2_k0_to_k1_to = 24 / 133

elbow_b15_o13_i1_M1_to_M2_k0_to_k1 : ElbowEvent
elbow_b15_o13_i1_M1_to_M2_k0_to_k1 = mkElbowEvidence
  cfg_b15_o13_i1_M1_to_M2_k0_to_k1
  ρ_b15_o13_i1_M1_to_M2_k0_to_k1_from
  ρ_b15_o13_i1_M1_to_M2_k0_to_k1_to
  refl  -- M-step: M-to ≡ suc M-from
  (k-step-suc 0)  -- k-increases: 0 < 1
  refl  -- density-weakly-improves: _≤ℚ_ density-from density-to ≡ true

-- End of auto-generated elbow events.
